title = "E-Ship Guy"

baseURL = "https://thedoubleh.github.io/eshipguy.com//"
theme = 'massively'
googleanalytics = "G-G9YFJN1TPH"
disqusShortname = "thedoubleh"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]